// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bklmurvbubzzhvhmgbil.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJrbG11cnZidWJ6emh2aG1nYmlsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAyODYwODEsImV4cCI6MjA2NTg2MjA4MX0.BepB-04YXlauDIapFkr_qUL7WCJPtrF913-Ad94L-KQ"
// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);