// Re-exportación de los componentes factorizados del sidebar
export {
  SidebarProvider,
  useSidebar,
  Sidebar,
  SidebarContent,
  SidebarHeader,
  SidebarTrigger,
  SidebarNav,
  SidebarNavItem,
  SidebarNavLink,
  SidebarFooter,
  SidebarGroup,
  SidebarGroupLabel,
  SidebarGroupContent,
  SidebarGroupItem,
  SidebarGroupItemLink,
  SidebarGroupItemButton,
  SidebarGroupItemIcon,
  SidebarGroupItemText,
  SidebarGroupItemBadge,
  SidebarGroupItemSeparator,
  SidebarGroupItemSkeleton,
  SidebarGroupItemInput,
  SidebarGroupItemSlot,
  SidebarMenu,
  SidebarMenuItem,
  SidebarMenuButton,
} from "./sidebar/index"
